all: main.c variables.c
	#----------------------BUILD----------------------
	gcc -g -Wall -o main main.c
	gcc -g -Wall -o variables variables.c
	#---------------------- FIN ----------------------

clean:
	$(RM) main
	$(RM) variables
